project_id = "atogozlqfwxztjyycjoy"

[functions.send-push-notification]
verify_jwt = true

[functions.create-checkout-session]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true

[functions.change-subscription-plan]
verify_jwt = true

[functions.stripe-payment-info]
verify_jwt = true

[functions.stripe-webhooks]
verify_jwt = false
